controller:
    socket: 'localhost:8080'

    auth:
        session_key: 'session_key'

        pwd_salt: 132784681

        token_salt: 128712

        secret: "SfouihcnswvUWIO_12f1biio"

db:
    dsn: 'dsn'
